"use strict";

const codes_definitions = {
	codes: [
		"1xx",
		100,
		101,
		102,
		103,
		"2xx",
		200,
		201,
		202,
		203,
		204,
		205,
		206,
		207,
		208,
		226,
		"3xx",
		300,
		301,
		302,
		303,
		304,
		305,
		306,
		307,
		308,
		"4xx",
		400,
		401,
		402,
		403,
		404,
		405,
		406,
		407,
		408,
		409,
		410,
		411,
		412,
		413,
		414,
		415,
		416,
		417,
		418,
		421,
		422,
		423,
		424,
		425,
		426,
		428,
		429,
		431,
		444,
		451,
		499,
		"5xx",
		500,
		501,
		502,
		503,
		504,
		505,
		506,
		507,
		508,
		510,
		511,
		599,
	],
	definitions: [
		"Informational",
		"Continue",
		"Switching Protocols",
		"Processing",
		"Early Hints",
		"Success",
		"Ok",
		"Created",
		"Accepted",
		"Non-Authoritative Information",
		"No Content",
		"Reset Content",
		"Partial Content",
		"Multi-Status",
		"Already Reported",
		"IM Used",
		"Redirection",
		"Multiple Choices",
		"Moved Permanently",
		"Found(Moved Temporarily)",
		"See Other",
		"Not Modified",
		"Use Proxy",
		"Switch Proxy",
		"Temporary Redirect",
		"Permanent Redirect",
		"Client Error",
		"Bad Request",
		"Unauthorized",
		"Payment Required",
		"Forbidden",
		"Not Found",
		"Method Not Allowed",
		"Not Acceptable",
		"Proxy Authentication Required",
		"Request Timeout",
		"Conflict",
		"Gone",
		"Length Required",
		"Precondition Failed",
		"Payload Too Large",
		"Request-URI Too Long",
		"Unsupported Media Type",
		"Requested Range Not Satisfiable",
		"Expectation Failed",
		"I'm a teapot",
		"Misdirected Request",
		"Unprocessable Entity",
		"Locked",
		"Failed Dependency",
		"Too Early",
		"Upgrade Required",
		"Precondition Required",
		"Too Many Requests",
		"Requested Header Fields Too Large",
		"Connect Closed Without Response",
		"Unavailable For Legal Reasons",
		"Client Closed Request",
		"Server Error",
		"Internal Server Error",
		"Not Implemented",
		"Bad Gateway",
		"Service Unavailable",
		"Gateway Timeout",
		"HTTP Version Not Supported",
		"Variant Also Negotiates",
		"Insufficient Storage",
		"Loop Detected",
		"Not Extended",
		"Network Authentication Required",
		"Network Connect Timeout Error",
	],
	explanations: [],
};

export default codes_definitions;
